version: '3.1'

services:
  nginx:
    image: nginx:1.15
    container_name: nginx
    volumes:
        - ./:/var/www
        - ./default.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - 80:80
    networks:
      - currency-networks
    depends_on:
      - flask
  flask: 
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: flask
    command: gunicorn --bind 0.0.0.0:8000 --workers 4 "app.main:create_app"
    volumes:
      - ./:/var/www
    networks:
      currency-networks:
         aliases:
         - flask-application   

networks: 
  currency-networks:
           